<?php

/**
 * @file
 * Contains geofield_suntimes.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;


/**
 * Implements hook_help().
 */
function geofield_suntimes_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the geofield_suntimes module.
    case 'help.page.geofield_suntimes':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides sunrise and sunset times based on location and date.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 */
function geofield_suntimes_theme() {
  return [
    'geofield_suntimes' => [
      'variables' => [
        'sunrise' => 0,
        'sunset' => 0,
        'solar_noon' => 0
      ],
    ],
  ];
}
